title: 我的博客
description: 分享我的想法和经验
url: https://ang-eiz.github.io/
baseurl: /

author: Zozo
twitter_username: 
social:
  name: zozo的博客
  links:
    - https://github.com/ang-eiz

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Collections
collections:
  posts:
    output: true
    permalink: /newblog/:name/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - .bundle